version: '3.7'

services:
  app:
    tty: true
    init: true
    image: node:10.13
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules:delegated
      - yarn-cache:/.yarn-cache
    working_dir: /app
    command: ['sh', '-c', 'yarn && node_modules/.bin/gulp']
    depends_on:
      - mongodb
    restart: on-failure
    ports:
      - "${PORT-6999}:80"
    environment:
      YARN_CACHE_FOLDER: /.yarn-cache
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI-mongodb://mongodb:27017}
      REDIS_URI: ${REDIS_URI-redis://redis:6379/0}
      PORT: ${PORT-6999}

  mongodb:
    tty: true
    image: mongo:3.4
    restart: always
    volumes:
      - mongodb:/data/db

  redis:
    tty: true
    image: redis:5-alpine
    restart: always

volumes:
  yarn-cache: {}
  mongodb: {}
